### ISSUE TITLE
Trouble with B528s-23a

### ISSUE THREAD

**Issue by novus213** [pearlxcore/Huawei-Router-Tool#1]
Hi,

When i try to change NetworkMode 03 to 0302 (cuz the software is brided in 4G & 4G+ only and o need to have 3G too), i have an error. 
125003 : ERROR_WRONG_SESSION_TOKEN
and i do again
125002 : ERROR_SESSION
([screenshot](http://prntscr.com/r8erhq))
my device info is [screenshot](http://prntscr.com/r8euc9)

Any suggestion ?

**Comment by pearlxcore** [comment]
That is because of the method i use is wrong. As the error threw is ERROR_WRONG_SESSION_TOKEN, the http POST I used didn't use the current session cookie and token. I will release the new update soon.

**Comment by pearlxcore** [comment]
I fixed this on latest update. But I have not uploaded the latest version yet. Sadly during this quarantine period I’m away from home. I can’t push any update until the quarantine period is over. Thanks for pointed this out.
