### ISSUE TITLE
not work with this modem

### ISSUE THREAD

**Issue by Constantine-HD** [pearlxcore/Huawei-Router-Tool#13]
your work is great but not work with this modem

Product Information
Model:
WBB Router30-22a
SN:
xxxxxxxxxxxxxxxxxxxxx
Hardware version:
Ver.B
Firmware version:
V100R001C01SPC110
Firmware build time:
10/4/2015 09:37:30

i use admin user and pass but not work 

user:ooredooadmin
pass:adminooredoo

**Comment by pearlxcore** [comment]
Maybe your router is not compatible with this program
