### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by iamnmber4** [pearlxcore/Huawei-Router-Tool#16]
Sorry im so noob that i dont know how to install this. Im just new ti github.

**Comment by pearlxcore** [comment]
https://github.com/pearlxcore/Huawei-Router-Tool/releases/tag/v1.1

In assets download the zip file

**Comment by iamnmber4** [comment]
I did downloaded the zip 

![image](https://user-images.githubusercontent.com/80436569/111064992-4a64bc80-84f2-11eb-8953-39d94c69294b.png)

then i run this but nothing happened.

![image](https://user-images.githubusercontent.com/80436569/111065010-636d6d80-84f2-11eb-88ec-42466a984231.png)

It's just like this.

![image](https://user-images.githubusercontent.com/80436569/111065017-7122f300-84f2-11eb-99d8-fb66609013c2.png)

**Comment by pearlxcore** [comment]
Not that one. https://github.com/pearlxcore/Huawei-Router-Tool/releases/download/v1.1/Huawei.Router.Tool.v1.1.zip

**Comment by iamnmber4** [comment]
I was able to install it. still looking where to login. Im using B535 932 with dashboard http://192.168.254.254/html/overview.html

![image](https://user-images.githubusercontent.com/80436569/111067064-438f7700-84fd-11eb-85ad-7258408648cf.png)

**Comment by pearlxcore** [comment]
Actually its a portable apps. No installation needed. You need to specify username, password and ip address in settings tab.

**Comment by iamnmber4** [comment]
It did work after restart.

![image](https://user-images.githubusercontent.com/80436569/111067161-ddefba80-84fd-11eb-9071-2447b0c8c456.png)

**Comment by pearlxcore** [comment]
> It did work after restart.
> 
> ![image](https://user-images.githubusercontent.com/80436569/111067161-ddefba80-84fd-11eb-9071-2447b0c8c456.png)

From this screenshot i can tell that the program is not working properly. It not displaying complete router info. This is the bug in the program I have not fix yet. But you can use v7 of the program, its the older version before i rewrote the whole program to 1.x. I will upload v7 to the repo later.

**Comment by iamnmber4** [comment]
Yes but the most important part is the band selection which is working.. super thank you for this.

**Comment by iamnmber4** [comment]
I was able to change bands. I'm just curious how to do CA.

![image](https://user-images.githubusercontent.com/80436569/111068651-9f113300-8504-11eb-9903-85368e7c1ffe.png)

**Comment by pearlxcore** [comment]
Just select which band you want to combine and apply

**Comment by xenoxavier** [comment]
One of my friends use it and he mentioned 2 network bands missing? Band 40 and band 41, he is using b315-936. im not sure how the fetching of network bands work.

**Comment by pearlxcore** [comment]
Those are the supported band by the router.

**Comment by JustusErima** [comment]
> Those are the supported band by the router.

Can I use this to reset if rooter is locked to a particular Simcard?

**Comment by pearlxcore** [comment]
no you cannot
