### ISSUE TITLE
Choose upload band | Aggregation of four download bands

### ISSUE THREAD

**Issue by mucke5** [pearlxcore/Huawei-Router-Tool#2]
Can you please also implement the independent **choice of the upload band** (on which it is currently not impossible to perform band aggregation)? The upload band can serve as the 'primary' band for the router.

With some Huawei routers it is also possible to aggregate up to **four** (instead of only three) bands for download (e.g. Huawei B618s-22d).

I would like to be able to use this functionality with my new router Huawei 5G CPE Pro (H112-372).
_So far only your tool works with the new router! Thanks a lot!!_ 

It would be very helpful to see this in an update, as this is the only way I can prefer certain LTE masts to achieve the maximum download and upload rate in my region.
~~~
LTEInspecteur does it that way, and I have successfully tested it on my old Huawei B618s-22d.
https://routeur4g.fr/discussions/discussion/67/lteinspecteur-logiciel-de-surveillance-des-routeurs-4g-huawei

**Comment by pearlxcore** [comment]
Hi @mucke5 . I’m glad you are using this tool. Well actually I made some update (pretty big update) for this tool. I recreated the band selection tool by getting every supported network band by the router and listed out for selection. So let say if you login the tool using B618, the program will only list the supported network band for B618. From there you can choose or lock up to 3 network band. But I shouldn’t put limit for choosing band. I will change that. Thanks for your suggestion.

For choosing band as upload band, I have less experience or knowledge for that. I checked the link you gave. The program is cool and have wider option for band selection tool. Maybe I can make it as reference for future update and hoping the program have the english translation.

However I have bigger problem at this moment. I’m currently at my parent house while my workstation and projects is far away at my home. I can’t do any update for now until this quarantine period is over. Here in Malaysia, if you cross between states without strong reason you will be charged.

Anyway thanks for your suggestion. Stay safe!

**Comment by mucke5** [comment]
Hi @pearlxcore . Hope you and your family are healthy and safe during these uncertain and unprecedented times! You might run into some difficulty now, but we have this ubiquitous experience that all of us are going through, on a spectrum.
I believe in your project and wait for your big update, maybe with the pre-selection of the download  bands _and upload band_ ;)

**Comment by mucke5** [comment]
I see you're back. I've been waiting anxiously for this ... =D

**Comment by pearlxcore** [comment]
Hi yeah I released v7, but then deleted it. I think I want to add some small addition to it. But please noted that in v7 I didn't include feature for upload bands as I have lack of info for that. I'm not sure which band available for upload. I used LTEInspecteur but don't really understand how the selection for upload band works.

**Comment by mucke5** [comment]
How is the progress?

**Comment by pearlxcore** [comment]
Sorry. Kinda busy these days. Have you try locking band for upload using LTEInspecteur? Does it work? I'm still figuring how the aggregation works. It's weird because I tried to lock upload band to a certain network band but it always locking on band 7.

**Comment by mucke5** [comment]
@pearlxcore the LTEInspecteur isn't working with my current 5G router, only your tool does ;-)
Maybe you can get an idea here, how to lock the upload band:
`https://github.com/tpoechtrager/Huawei_Tool/blob/master/LTE_1800%2B2100_UPLOAD_2100.sh
https://drive.google.com/drive/folders/1sNp3irI6zbQ04r9_NCOL5HXfQHQNN3RZ`

**Comment by pearlxcore** [comment]
The script locks band 1, then locking band 1+ 3?

**Comment by mucke5** [comment]
> I'm no expert, but whenever [...] I first force it onto just B1 or B3 (so only one band in use and only 4G speeds). [...] I then [...] set [...] back to Auto (or B1+B3+B20) and [...] will **STAY ON THE BAND I FORCED IT ONTO** but will now also have the other bands available to aggregate with.
And I then confirm this by [...] observing it is still actually using whichever of B1 or B3 I previously forced it onto, that it's now set to Auto for available bands (indicated by F/TDD) and it's back to indicating that it's using 4G+ speeds.
`https://www.ispreview.co.uk/talk/threads/huawei-b535-232-4g-lte-router-issue.36112/page-8`

Another App offering the Configuration Radio (even for 5G): 
`https://ltehmonitor.github.io/#DetailedConfiguration`

**Comment by pearlxcore** [comment]
That tool is the perfect toolbox for Huawei routers. I'm amazed. Thanks for showing me the tool. I added 5G option and upload band for band aggregation ;)

**Comment by mucke5** [comment]
@pearlxcore The new release is fantastic. I'm only missing the _Network Mode Quick Switch_ **Auto** ;)

**Comment by pearlxcore** [comment]
Oh shoot how can I missed that.

Fixed.

**Comment by mucke5** [comment]
@pearlxcore Happens. One more tiny change, the ribbon _WLAN Tools_ replaced by name _Network Tools_ fits better, when looking at the tools in this ribbon ;)

**Comment by pearlxcore** [comment]
Changed the name. Thanks for suggestion.
