### ISSUE TITLE
Huawei Router Tool error

### ISSUE THREAD

**Issue by tulips13** [pearlxcore/Huawei-Router-Tool#4]
Hi pearlxcore,

I downloaded Huawei Router Tool but there is no luck in compiling it. It says that Huawei Router Tool.exe is missing

**Comment by pearlxcore** [comment]
Hi. You tried to compile the project? Can you provide any screenshot of the error?

**Comment by tulips13** [comment]
It is working fine now. Thank you for your wonderful work.


Sent from Yahoo Mail for iPhone


On Wednesday, May 13, 2020, 6:42 AM, pearlxcore <notifications@github.com> wrote:




Hi. You tried to compile the project? Can you provide any screenshot of the error?
