### ISSUE TITLE
Support for 5G?

### ISSUE THREAD

**Issue by teepean** [pearlxcore/Huawei-Router-Tool#5]
Hello and thank you for this great tool! I recently upgraded to Huawei 5G CPE Pro and would like to know what it would need to get a support for that device? I can dowload whatever configuration file is needed and have used Binwalk to uncompress an update firmware.

EDIT: I have to mention that tool works currently except for the 5G part.

**Comment by pearlxcore** [comment]
Hi. Thanks for using this tool. For this I will need my hands on a 5G routers for testing. I don't know what API used in 5G routers. It may be differ with the current 4G routers. Or maybe you can extract the firmware update and search for the API i guess in js folder and share it to me? Also what do you mean by 5G part that is not working?

**Comment by teepean** [comment]
I meant with 5G not working that I can select 2G, 3G, 4G or Auto but there is no option to select 5G.

Here's an extracted firmware from an update and some files I have downloaded from my router.

https://www.mediafire.com/file/gr1z11cf75mh7hc/5GCPEPro.zip/file

**Comment by pearlxcore** [comment]
I couldnt find any js file in the files you provided

**Comment by teepean** [comment]
Which ones do you need? There are a lot of lua files in the extracted firmware and their names are similar to js files.

**Comment by pearlxcore** [comment]
Since I don't have any 5G router, can you make some test for me. On API control tab, select "api/net/net-mode" and see the 'NetworkMode' element. 

00 for Auto.
01 for 2G
02 for 3G
03 for 4G

So for 5G maybe the value is 04? You can test by changing 'NetworkMode' to 04 send the post request on the right window.

**Comment by teepean** [comment]
It gives an error if I change it to 04. 

`Request failed: ERROR 112003: 
ERROR_SET_NET_MODE_AND_BAND_FAILED`

Changing it 03 works.

Here is "api/net/net-mode-list". I assume it shows the possible modes?

`<response>
  <AccessList>
    <Access>00</Access>
    <Access>08</Access>
    <Access>03</Access>
  </AccessList>
  <BandList>
    <Band>
      <Name>GSM900/GSM1800/WCDMA2100</Name>
      <Value>400380</Value>
    </Band>
    <Band>
      <Name>GSM850/GSM1900/WCDMA850</Name>
      <Value>4280000</Value>
    </Band>
    <Band>
      <Name>All bands</Name>
      <Value>3fffffff</Value>
    </Band>
  </BandList>
  <LTEBandList>
    <LTEBand>
      <Name>LTE BC1/LTE BC3/LTE BC5/LTE BC7/LTE BC8/LTE BC20/LTE BC28/LTE BC32/LTE BC34/LTE BC38/LTE BC39/LTE BC40/LTE BC41/LTE BC42/LTE BC43</Name>
      <Value>7e2880800d5</Value>
    </LTEBand>
    <LTEBand>
      <Name>All bands</Name>
      <Value>7fffffffffffffff</Value>
    </LTEBand>
  </LTEBandList>
</response>`

**Comment by teepean** [comment]
I found a file called api/net/net-feature-switch

Could you add that to the program?

`<?xml version="1.0" encoding="UTF-8"?>
<response>
<net_premode_switch>2</net_premode_switch>
<`>0</lteband_switch>
</response>
`

**Comment by pearlxcore** [comment]
> 
> 
> I found a file called api/net/net-feature-switch
> 
> Could you add that to the program?
> 
> `<?xml version="1.0" encoding="UTF-8"?> <response> <net_premode_switch>2</net_premode_switch> <>0</lteband_switch> </response> `

Will add it.

> 
> 
> It gives an error if I change it to 04.
> 
> `Request failed: ERROR 112003: ERROR_SET_NET_MODE_AND_BAND_FAILED`
> 
> Changing it to 03 works.
> 
> Here is "api/net/net-mode-list". I assume it shows the possible modes?
> 
> `
> 
> ```
> <Access>00</Access>
> 
> <Access>08</Access>
> 
> <Access>03</Access>
> ```
> 
> ```
> <Band>
> 
>   <Name>GSM900/GSM1800/WCDMA2100</Name>
> 
>   <Value>400380</Value>
> 
> </Band>
> 
> <Band>
> 
>   <Name>GSM850/GSM1900/WCDMA850</Name>
> 
>   <Value>4280000</Value>
> 
> </Band>
> 
> <Band>
> 
>   <Name>All bands</Name>
> 
>   <Value>3fffffff</Value>
> 
> </Band>
> ```
> 
> ```
> <LTEBand>
> 
>   <Name>LTE BC1/LTE BC3/LTE BC5/LTE BC7/LTE BC8/LTE BC20/LTE BC28/LTE BC32/LTE BC34/LTE BC38/LTE BC39/LTE BC40/LTE BC41/LTE BC42/LTE BC43</Name>
> 
>   <Value>7e2880800d5</Value>
> 
> </LTEBand>
> 
> <LTEBand>
> 
>   <Name>All bands</Name>
> 
>   <Value>7fffffffffffffff</Value>
> 
> </LTEBand>
> ```
> 
> `

Hmm. I couldn't figure out what is the value for 5G. You already on 5G line?

**Comment by teepean** [comment]
> I believe those are all supported band by your router. Still couldn't figure out what is the value for 5G. You already on 5G line?

00 is Auto
03 is 4G
08 is 3G

Nothing else seems to work.

**Comment by pearlxcore** [comment]
> > I believe those are all supported band by your router. Still couldn't figure out what is the value for 5G. You already on 5G line?
> 
> 
> 
> 00 is Auto
> 
> 03 is 4G
> 
> 08 is 3G
> 
> 
> 
> Nothing else seems to work.
> 
> 
> 
> 

Wait, the values are different.

On 4G Lte router/modem these are the values :


00 for Auto.
01 for 2G
02 for 3G
03 for 4G

**Comment by pearlxcore** [comment]
Maybe Huawei will release a new firmware update for 5G compatibility when it rollout next year

**Comment by pearlxcore** [comment]
I added 5G option and upload band for band aggregation ;)

https://github.com/pearlxcore/Huawei-Router-Tool/releases/tag/v7
