### ISSUE TITLE
RSRQ readout faulty on B818

### ISSUE THREAD

**Issue by salzrat** [pearlxcore/Huawei-Router-Tool#7]
When clicking on  Signal Monitor, dozens of dialog boxes with "RSRQ Parsing Error" pop up.

On the device info page, RSRQ is displayed correctly, though...

I believe this is because the B818 formats the RSRQ with one decimal digit (e.g., -10.0). The conversion to a numbers probably fails then.

**Comment by pearlxcore** [comment]
Can you show response on "api/device/signal"?

**Comment by salzrat** [comment]
`<response>
  <pci>415</pci>
  <sc></sc>
  <cell_id>xxx</cell_id>
  <rsrq>-13.0dB</rsrq>
  <rsrp>-92dBm</rsrp>
  <rssi>-57dBm</rssi>
  <sinr>10dB</sinr>
  <rscp></rscp>
  <ecio></ecio>
  <mode>7</mode>
  <ulbandwidth>20MHz</ulbandwidth>
  <dlbandwidth>20MHz</dlbandwidth>
  <txpower>PPusch:5dBm PPucch:-8dBm PSrs:0dBm PPrach:-4dBm</txpower>
  <tdd></tdd>
  <ul_mcs>mcsUpCarrier1:24</ul_mcs>
  <dl_mcs>mcsDownCarrier1Code0:1 mcsDownCarrier1Code1:20</dl_mcs>
  <earfcn>DL:3350 UL:21350</earfcn>
  <rrc_status>1</rrc_status>
  <rac></rac>
  <lac></lac>
  <tac>xxx</tac>
  <band>7</band>
  <nei_cellid>No1:xxx</nei_cellid>
  <plmn>23205</plmn>
  <ims>0</ims>
  <wdlfreq></wdlfreq>
  <lteulfreq>25600</lteulfreq>
  <ltedlfreq>26800</ltedlfreq>
  <transmode>TM[4]</transmode>
  <enodeb_id>xxx</enodeb_id>
  <cqi0>15</cqi0>
  <cqi1>127</cqi1>
  <ulfrequency>2560000kHz</ulfrequency>
  <dlfrequency>2680000kHz</dlfrequency>
  <arfcn></arfcn>
  <bsic></bsic>
  <rxlev></rxlev>
</response>`

**Comment by pearlxcore** [comment]
Yeah the rsrq value is in 1 decimal point. I used int.TryParse. Change to double.TryParse may solve the problem.

**Comment by salzrat** [comment]
Yes, but maybe you need an "InvariantCulture" parameter, as the decimal symbol may change between locales, but I think the router output will always use a ".". Looking forward to an updated release :)

**Comment by salzrat** [comment]
So is it fixed? I don't see a new version yet...

**Comment by pearlxcore** [comment]
Check the new release

https://github.com/pearlxcore/Huawei-Router-Tool/releases/tag/v7

**Comment by salzrat** [comment]
This now works, but there's another problem I'll report separately.
