### ISSUE TITLE
Add other band selection

### ISSUE THREAD

**Issue by oatmeal01** [pearlxcore/Huawei-Router-Tool#8]
Please add other band selections from the list like B28, B41 etc. and add also auto change wanip. Just strip this android app's assets. Thanks alot!
 [Huawei Manager.apk](https://drive.google.com/uc?authuser=0&id=13kS4FssClyNRvks63PPhzSEbFLaE8nK_&export=download) 

B310As-938: Bands(3,28,41)
B315s-936: Bands(1,3,40,41)

**Comment by pearlxcore** [comment]
Check the new release

https://github.com/pearlxcore/Huawei-Router-Tool/releases/tag/v7
