### ISSUE TITLE
Unhandled exception in v7

### ISSUE THREAD

**Issue by salzrat** [pearlxcore/Huawei-Router-Tool#9]
When I start the app, I receive an error. I can continue and most things work, but the router info between serial number and wan ip address is not shown. Also, the "remember me" doesn't work (on next start, IP address etc. is empty):

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4069.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Huawei Router Tool
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wimmer/Downloads/drivers/b715/Huawei.Router.Tool-v7.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.2.0.3
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wimmer/Downloads/drivers/b715/Huawei.Router.Tool-v7.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.2.0.3
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wimmer/Downloads/drivers/b715/Huawei.Router.Tool-v7.exe
----------------------------------------
Semver
    Assembly Version: 2.0.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wimmer/Downloads/drivers/b715/Huawei.Router.Tool-v7.exe
----------------------------------------
Octokit
    Assembly Version: 0.3.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wimmer/Downloads/drivers/b715/Huawei.Router.Tool-v7.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pearlxcore** [comment]
Is this continuously occurred? I don't see any error while using v7 on B525s

**Comment by salzrat** [comment]
Yes, whenever I start the app, immediately when displaying the UI, before any router connection... Maybe you require a certain .net version?

**Comment by pearlxcore** [comment]
You may need [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48)

**Comment by salzrat** [comment]
I do have 4.8 installed.

**Comment by oatmeal01** [comment]
the app freezes when logging in and out/send or receive sms(the app sms does not support B310As-938).
